name: Update phim.json
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cài thư viện và chạy script
        run: |
          npm install jsdom node-fetch
          node script.js

      - name: Đảm bảo thư mục json và file phim.json tồn tại
        run: |
          mkdir -p json
          if [ ! -f json/phim.json ]; then
            echo "[]" > json/phim.json
          fi

      - name: Commit thay đổi
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add json/phim.json
          git commit -m "auto update phim.json" || echo "Không có thay đổi"
          git push
